/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RemoteService_constants.h"

namespace remote {

const RemoteServiceConstants g_RemoteService_constants;

RemoteServiceConstants::RemoteServiceConstants() {
}

} // namespace

