/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RemoteService_CONSTANTS_H
#define RemoteService_CONSTANTS_H

#include "RemoteService_types.h"

namespace remote {

class RemoteServiceConstants {
 public:
  RemoteServiceConstants();

};

extern const RemoteServiceConstants g_RemoteService_constants;

} // namespace

#endif
